name: "Generate an index for the Overture Maps release and create a PR"
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version"
        required: true
        type: string
  workflow_call:
    inputs:
      releaseVersion: 
        description: "Release version"
        required: true
        type: string

env:
  PYTHON_VERSION: 3.12
  COLUMNS: 120

jobs:
  generate-release-index:
    name: Generate an index for the Overture Maps ${{ inputs.releaseVersion }} release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.CICD_PAT_TOKEN }}
      - name: Configure Git user
        run: |
          git config --local user.name "Kraina CI/CD"
          git config --local user.email "cicd@kraina.ai"
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python script
        run: python generate_release_index.py "${{ inputs.releaseVersion }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: ${{ format('feat(CI/CD){0} add {1} release index', ':', inputs.releaseVersion) }}
          branch: ${{ format('release/{0}', inputs.releaseVersion) }}
          labels: release
          base: main
          token: ${{ secrets.CICD_PAT_TOKEN }}
          author: Kraina CI/CD <cicd@kraina.ai>
          committer: Kraina CI/CD <cicd@kraina.ai>
          commit-message: ${{ format('feat(CI/CD){0} add {1} release index', ':', inputs.releaseVersion) }}